import { QueryProvider } from "@/lib/providers/QueryProvider";
import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body>
      <QueryProvider>
          {children}
      </QueryProvider>
        </body>
    </html>
  );
}
